name: build v3
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - v3/**
jobs:
  push:
    name: "yolks:${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - v3
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./v3
          file: ./${{ matrix.tag }}/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/pelican-eggs/yolks:${{ matrix.tag }}
            ghcr.io/parkervcp/yolks:${{ matrix.tag }}
